spring.application.name=loan-comparison-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true
spring.flyway.location=classpath:db/migration

loan.application.expiry.seconds=86400
